config/routes.rb
Mgr::Application.routes.draw do
  

  devise_for :users, 
  :controllers => { :sessions => "users/sessions",
                    :registrations => "users/registrations",
                    :passwords => "users/passwords"}

  root :to => "gpx#index"
  match '/about' ,:to => "gpx#about"
  match '/old_broswer', :to => "gpx#old_broswer"

  resources :locations do
   collection do 
    get 'load_location'
    delete 'destroy_checked'
    put 'update_location'
    get 'show_photos'
    post 'create_from_map'
    get 'check_name'
    get 'download_gpx'
   end 
 end
  
  resources :users,:only =>[:show,:index] do 
   collection do
    get 'profile'
   end
   resources :photos
  end
  
  resources :friendships, :only=>[:create, :destroy] do 
    collection do
      delete 'destroy_send_invite'
      delete 'destroy_invited'
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  replicated_model()
  has_many :locations
  has_many :photos
  has_many :friendships
  has_many :friends, :through => :friendships 
  has_many :inverse_friendships, :class_name => "Friendship", :foreign_key => "friend_id"
  has_many :inverse_friends, :through => :inverse_friendships, :source => :user
  
  devise :database_authenticatable, :registerable,
         :recoverable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name,:second_name
  # attr_accessible :title, :body
  
  def location_exist?(name)
    object = self.locations.find_by_name(name)
    object.nil? ? true : false
  end
  # czy ma przyjaźń
  def self.friends?(user1,user2)
    user1.friendships.where(friend_id: user2.id).exists? && user2.friendships.where(friend_id: user1.id).exists?
  end
  # czy current_user został zaproszony przez usera
  def invited?(user)
    inverse_friendships.where(user_id: user.id).empty?
  end
  
  # czy current_user wysłał zaproszenie
  def send_invite?(user)
    friendships.where(friend_id: user.id).exists?
  end
  
  def self.destroy_account(user)
    User.transaction do 
      user.locations.destroy_all
      user.photos.using(:shard_1).destroy_all
      user.friendships.destroy_all
      user.inverse_friendships.destroy_all
      user.destroy
    end
  end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < DeviseController
  #prepend_before_filter :require_no_authentication
  # Render the #edit only if coming from a reset password email link
  #append_before_filter :assert_reset_token_passed, :only => :edit

  def new
    build_resource({})
  end

  def create
    self.resource = resource_class.send_reset_password_instructions(resource_params)
    if successfully_sent?(resource)
      respond_with({}, :location => after_sending_reset_password_instructions_path_for(resource_name))
    else
      flash[:alert] = resource.errors.values.sum
      respond_with(resource)
    end
  end

  def edit
    self.resource = resource_class.new
    resource.reset_password_token = params[:reset_password_token]
    render :template => 'users/passwords/edit'
  end

  def update
    self.resource = resource_class.reset_password_by_token(resource_params)
    if resource.errors.empty?
      resource.unlock_access! if unlockable?(resource)
      flash_message = resource.active_for_authentication? ? :updated : :updated_not_active
      set_flash_message(:notice, flash_message) if is_navigational_format?
      sign_in(resource_name, resource)
      respond_with resource, :location => after_sign_in_path_for(resource)
    else
      flash[:alert]= resource.errors.values.sum
      respond_with resource
    end
  end

  protected

    # The path used after sending reset password instructions
    def after_sending_reset_password_instructions_path_for(resource_name)
      new_session_path(resource_name)
    end

    # Check if a reset_password_token is provided in the request
    def assert_reset_token_passed
      if params[:reset_password_token].blank?
        set_flash_message(:error, :no_token)
        redirect_to new_session_path(resource_name)
      end
    end

    # Check if proper Lockable module methods are present & unlock strategy
    # allows to unlock resource on password reset
    def unlockable?(resource)
      resource.respond_to?(:unlock_access!) &&
        resource.respond_to?(:unlock_strategy_enabled?) &&
        resource.unlock_strategy_enabled?(:email)
    end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  before_filter :authenticate_user!, :except => [:new,:create]
  before_filter :load_user, :only =>[:show,:edit,:destroy]
  prepend_before_filter :require_no_authentication, :only => [ :new, :create, :cancel ]
  prepend_before_filter :authenticate_scope!, :only => [:edit, :update, :destroy]
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])
    url = if @user.save && @user.active_for_authentication?
      sign_in(resource_name, resource)
      user_path(@user)
    else
      flash[:alert] = @user.errors.values.sum
      new_user_registration_path
    end
    redirect_to url
  end
  
  def show
  end
  
  def edit
  end
  
  def update
    self.resource = resource_class.to_adapter.get!(send(:"current_#{resource_name}").to_key)
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)

    if resource.update_with_password(resource_params)
      if is_navigational_format?
        flash_key = update_needs_confirmation?(resource, prev_unconfirmed_email) ?
          :update_needs_confirmation : :updated
        set_flash_message :notice, flash_key
      end
      sign_in resource_name, resource, :bypass => true
      #respond_with resource, :location => after_update_path_for(resource)
      redirect_to profile_users_path(resource)
    else
      clean_up_passwords resource
      respond_with resource
    end
  end
  
  def cancel
  end
  
  def destroy
    User.destroy_account(@user)
      Devise.sign_out_all_scopes ? sign_out : sign_out(resource_name)
      set_flash_message :notice, :destroyed if is_navigational_format?
      respond_with_navigational(@user){ redirect_to after_sign_out_path_for(resource_name) }
  end
  
  private
  
  def load_user
    @user = User.find_by_id(params[:id]) 
  end
  
  protected

  def update_needs_confirmation?(resource, previous)
    resource.respond_to?(:pending_reconfirmation?) &&
      resource.pending_reconfirmation? &&
      previous != resource.unconfirmed_email
  end

  # Build a devise resource passing in the session. Useful to move
  # temporary session data to the newly created user.
  def build_resource(hash=nil)
    hash ||= resource_params || {}
    self.resource = resource_class.new_with_session(hash, session)
  end

  # Signs in a user on sign up. You can overwrite this method in your own
  # RegistrationsController.
  def sign_up(resource_name, resource)
    sign_in(resource_name, resource)
  end

  # The path used after sign up. You need to overwrite this method
  # in your own RegistrationsController.
  def after_sign_up_path_for(resource)
    after_sign_in_path_for(resource)
  end

  # The path used after sign up for inactive accounts. You need to overwrite
  # this method in your own RegistrationsController.
  def after_inactive_sign_up_path_for(resource)
    respond_to?(:root_path) ? root_path : "/"
  end

  # The default url to be used after updating a resource. You need to overwrite
  # this method in your own RegistrationsController.
  def after_update_path_for(resource)
    signed_in_root_path(resource)
  end

  # Authenticates the current scope and gets the current resource from the session.
  def authenticate_scope!
    send(:"authenticate_#{resource_name}!", :force => true)
    self.resource = send(:"current_#{resource_name}")
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController<Devise::SessionsController

  before_filter :authenticate_user!, :only => [:destroy]
  
  def new
  end
  
  def create
    resource = warden.authenticate!(:scope => resource_name, :recall => "#{controller_path}#new")
    sign_in(resource_name,resource)
    flash[:notice] = I18n.t :signed_in, :scope=>[:devise,:sessions]
    redirect_to user_path(current_user)
  end
  
  def destroy
    sign_out(@user)
    flash[:notice] = I18n.t :signed_out, :scope=>[:devise,:sessions]
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  include ApplicationHelper
  
  before_filter :authenticate_user!
  before_filter :load_user
  before_filter :user_authorize, :only =>[:show]

    
  def index
    @search= User.search(params[:q])
    user_array = @search.result
    @users = Kaminari.paginate_array(user_array).page(params[:page]).per(10)
  end
  
  def show
    @location_file = @user.locations.new
    @location_name = locations_name_to_array
    @photo = @user.photos.using(:shard_1).new
  end
  
  def profile
    @location_name = locations_name_to_array
  end

  private
  
  def load_user
    @user = User.using(:master).find_by_id(params[:id]) 
    @user = @user ? @user : current_user 
  end
  
  def user_authorize
    authorize_user(@user)
  end
  
  def locations_name_to_array
    loc_name = @user.locations.select('DISTINCT name')
    name_array = []
    loc_name.each do |ln|
      name_array.push(ln.name)
    end
    name_array
  end
end

app/views/users/partials/_add_file.html.erb
<div id="add_gpx">
  <%= form_for @location_file, :html => {:mulitpart => true} do |f| %>
  <div class="box_form">
  <ul>
    <li><%= f.label "Name:",:size=> 22,:class=>"text" %></li>
    <li><%= f.text_field :name ,:size=> 22 ,:class=>"wpis"%></li>
    <li><%= f.file_field :gpx ,:size=> 22 ,:class=>"file"%></li>
    <li><%= f.label "Range:[50m-1000m]" ,:size=> 22,:class=>"text" %></li>
    <li><%= f.text_field :range ,:size=> 22 ,:class=>"wpis"%></li>
    <li><%= f.submit "Wyślij plik", :class => "submit" %></li>
  </ul>
  </div>
  <% end %>
</div>

app/views/users/partials/_friendship.html.erb
<div id="profile">
<%= load_friend(@user) %>
</div>

app/views/users/partials/_gpx_action.html.erb
<ul>
<li><div class="load_gpx_name"></div></li>
<li><%= link_to "Wrzytaj GPX", "#",:class=> "load_list_gpx"%>
    <%= render :partial => "users/partials/load_location"%>
</li>
<% if @user == current_user %>
<li><%= link_to "Dodaj GPX", "#",:class=> "add_gpx"%>
    <ul>
      <li>
        <%= render :partial => "users/partials/add_file"%>
      </li>
    </ul>
</li>


<li><%= link_to "Nowy GPX","#",:class=> "new_gpx"%>
  <spam class="new_gpx_points">
  <ul>
    <li><%= link_to "Zapisz","#",:class => "add_new_markers"%></li>
    <li><%= link_to "Wyczyść","#",:class =>"clear_all_new_markers" %></li>
  </ul>
  </spam>
</li>
<li><%=link_to "Edytuj GPX","#",:class=> "edit_gpx"%></li>
  <ul>
    <spam class="edit_gpx_points">
      <li><%= link_to "Usuń", "#",:class=> "get_markers_to_remove"%>
	<spam class="remove_gpx_points">
	  <ul>
	    <li><%= link_to "Zapisz","#",:class =>"set_markers_to_remove" %></li>
	    <li><%= link_to "Wyczyść","#",:class =>"clear_all_markers_to_remove" %></li>
	  </ul>
	</spam>
      </li>
      <li><%= link_to "Dodaj","#",:class=>"create_new_markers"%>
	<spam class="add_gpx_points">
	  <ul>
	    <li><%= link_to "Zapisz","#",:class => "add_new_markers"%></li>
	    <li><%= link_to "Wyczyść","#",:class =>"clear_all_new_markers" %></li>
	  </ul>
	</spam>
      </li>
    </spam></ul>
      <li><%= link_to "Profil terenu", "#", :class=>"profile_area"%>
        <%= render :partial => "users/partials/profile_buttons"%>
      </li>
<% end %>
</ul>

app/views/users/partials/_gpx_list.html.erb
  <table class="gpx_list">
    <spam class="table_title">Pliki gpx użytkownika:</spam>
    <tr>
      <th></th>
      <th></th>
    </tr>
    <% @location_name.each do |file_name|%>
      <tr>
        <td><%= file_name %> </td>
        <% if @user == current_user %>
	 <td> <%= link_to t('view.link.delete'), location_path(file_name), :method => :delete,:confirm => true %></td>
         <td> <%= link_to t('view.link.download'), download_gpx_locations_path(file_name) %></td>
        <% end %>
      </tr>
    <% end %>
  </table>

app/views/users/partials/_legend.html.erb
<ul class="legend">
  <i class="legend_title">Legenda:</i>
    <li>
      <%= image_tag "http://maps.google.com/mapfiles/kml/pal2/icon13.png"%>
      <i>Punkt.</i>
    </li>
    <li>
      <%= image_tag "http://maps.google.com/mapfiles/kml/pal3/icon46.png" %>
      <i>Nowy punkt.</i>
    </li>
    <li>
      <%= image_tag "http://maps.google.com/mapfiles/kml/pal3/icon39.png" %>
      <i>Punkt do usunięcia.</i></li>
    <li>
      <%= image_tag "camera.png"%>
      <i>Punkt posiadający zdjęcie/a.</i>  
    </li>
</ul>

app/views/users/partials/_load_location.html.erb
<ul class="list_locations">
  <li><%=select_tag "name", options_for_select(@location_name),:multiple=> true  %></li>
</ul>

app/views/users/partials/_profile_buttons.html.erb
<ul class="profile_buttons">
 <li><%= link_to "Zaznacz", "#",:class=>"check_marker"%></li>
 <li><%= link_to "Rysuj", "#", :class=> "draw_chart"%></li>
 <li><%= link_to "Wyczyść", "#",:class=>"clear_polyline"%></li>
</ul>