config/routes.rb
Mgr::Application.routes.draw do
  

  devise_for :users, 
  :controllers => { :sessions => "users/sessions",
                    :registrations => "users/registrations",
                    :passwords => "users/passwords"}

  root :to => "gpx#index"
  match '/about' ,:to => "gpx#about"
  match '/old_broswer', :to => "gpx#old_broswer"

  resources :locations do
   collection do 
    get 'load_location'
    delete 'destroy_checked'
    put 'update_location'
    get 'show_photos'
    post 'create_from_map'
    get 'check_name'
    get 'download_gpx'
   end 
 end
  
  resources :users,:only =>[:show,:index] do 
   collection do
    get 'profile'
   end
   resources :photos
  end
  
  resources :friendships, :only=>[:create, :destroy] do 
    collection do
      delete 'destroy_send_invite'
      delete 'destroy_invited'
    end
  end
end

app/models/photo.rb
class Photo < ActiveRecord::Base

  belongs_to :user
  belongs_to :location
  skip_callback :destroy, :after, :remove_image!
  
  attr_accessible :description, :image, :name, :location_id,:public_status
  mount_uploader :image, ImageUploader
  
  validates :name,    presence: true
  validates :image,    presence: true
  validates :description,    presence: true
  validates :location_id,    presence: true 
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  include ApplicationHelper
  
  around_filter :select_shard
  before_filter :authenticate_user!
  before_filter :load_user
  before_filter :load_photo, :only=>[:show,:destroy,:edit,:update]

  def index
    Octopus.using(:shard_1) do 
      @photos = Photo.find_all_by_user_id(@user.id)
    end
  end
  
  def new
  end
  
  def show
  end
  
  def create
    respond_to do |format| 
      @photo = Photo.using(:shard_1).new(params[:photo])
      @photo.user_id = @user.id
      @photo_id = @photo.location_id 
      if @photo.save
        format.js 
      end
    end
  end
  
  def edit
  end
  
  def update
    if @photo.update_attributes(params[:photo])
      flash[:notice]="Poprawnie zapisano zmiany."
    else
      flash[:alert] ="Blad akutalizacji."
    end
    redirect_to user_photos_path
  end
  
  def destroy
    if @photo.destroy
      flash[:notice] = t(:success, :scope => [:controller, :photo, :destroy]) 
    else
      flash[:alert] = t(:faild, :scope => [:controller, :photo, :destroy])
    end
    redirect_to user_photos_path
  end
  
  private
  
  def load_user
    Octopus.using(:master) do
      @user = User.find(params[:user_id])
    end
  end

  def load_photo
    @photo = Photo.using(:shard_1).find(params[:id])
  end
  
  
  def select_shard(&block)
    Octopus.using(:master, &block)
  end
end

app/helpers/photo_helper.rb
module PhotoHelper
end

app/views/photos/create.js.erb
<%= remotipart_response do %>
   $.fancybox.close();
   change_marker_icon(<%= @photo_id %>);// maps.js
   right_click_marker_action(); // markers_action.js odświerza akcje righ_clik na markerze
<% end %>

app/views/photos/edit.html.erb
<div class="session_form">
<center>
<%= form_for @photo ,:url => user_photo_path() do |f|%>
   <div>
     <%= image_tag @photo.image_url(:thumb) %>
   </div>
   <div>
    <%= f.label :name, "Nazwa" %>
    <%= f.text_field :name %>
   </div>
   <div>
    <%= f.label :description, "Opis:"%>
    <%= f.text_area :description, :size => "30x7" %>
   </div>
   <div>
     <%= f.label :public_status, "Publiczne ?"%>
     <i>(Czy zdjęcie ma być dostępne dla innych użytkowników ?)</i>
     <%= f.check_box :public_status %></div>
   <div>
   <%= f.submit "Zapisz" %></div>
<% end %>
   <p><%= link_to "Anuluj",user_photos_path(),:class=>"delete_acount" %></p>
</center>
</div>

app/views/photos/index.html.erb
<%=content_for :title,"Galery"%>
<div id="galery">
  <% @photos.each do |p|%>
    <% if p.public_status %>
           <div class="image_container">

        <div class="image">
        <center>
	  <%= link_to(image_tag(p.image_url(:thumb).to_s), p.image_url.to_s,:rel=> "image_group",:title =>p.description.to_s )%>
	</center>
	</div>

      <div class="name_image">
        <p><%= p.name %></p>
      </div>
      <% if @user == current_user %>
      <div class="action_image">
        <%= link_to t('view.link.edit'),edit_user_photo_path(@user,p)%>
        <%= link_to t('view.link.delete') ,
            user_photo_path(@user,p),
            :confirm => 'Czy napewno chcesz usunąć?',
            :method => :delete %>
      </div>
      <% end %>
    </div>
    <% elsif !p.public_status && @user == current_user %>
        <div class="image_container">

        <div class="image">
        <center>
	  <%= link_to(image_tag(p.image_url(:thumb).to_s), p.image_url.to_s,:rel=> "image_group",:title =>p.description.to_s )%>
	</center>
	</div>

      <div class="name_image">
        <p><%= p.name %></p>
      </div>
      <div class="action_image">
        <%= link_to t('view.link.edit'),edit_user_photo_path(@user,p)%>
        <%= link_to t('view.link.delete') ,
            user_photo_path(@user,p),
            :confirm => 'Czy napewno chcesz usunąć?',
            :method => :delete %>
      </div>
    </div>
    <% end %>

  <%end%>
</div>