config/routes.rb
Mgr::Application.routes.draw do
  

  devise_for :users, 
  :controllers => { :sessions => "users/sessions",
                    :registrations => "users/registrations",
                    :passwords => "users/passwords"}

  root :to => "gpx#index"
  match '/about' ,:to => "gpx#about"
  match '/old_broswer', :to => "gpx#old_broswer"

  resources :locations do
   collection do 
    get 'load_location'
    delete 'destroy_checked'
    put 'update_location'
    get 'show_photos'
    post 'create_from_map'
    get 'check_name'
    get 'download_gpx'
   end 
 end
  
  resources :users,:only =>[:show,:index] do 
   collection do
    get 'profile'
   end
   resources :photos
  end
  
  resources :friendships, :only=>[:create, :destroy] do 
    collection do
      delete 'destroy_send_invite'
      delete 'destroy_invited'
    end
  end
end

app/views/layouts/partials/_flash_info.html.erb
<div id="info" <%= flash.blank? ? "" :"style='display: block'" %>>
    <% unless flash.blank? %>
      <%= show_info(flash) %>
    <% end %>
</div>

app/views/layouts/partials/_front_menu.html.erb
<div class="front_menu">
  <ul>
  <% if user_signed_in?%>
    <li><%= link_to "#{current_user.email}", user_path(current_user)%></li>
    <li><%= link_to "Wyloguj się", destroy_user_session_path, :method =>:delete %></li>
  <% else %>
    <li><%= link_to "Zaloguj się", new_user_session_path %></li>
    <li><%= link_to "Zarejestruj się", new_user_registration_path %></li>
  <% end %>
  </ul>
</div>

app/views/layouts/partials/_header.html.erb
<header id="outside">
  <div class="logo">
    <%= link_to(image_tag("logo2.png"), root_path)%>
  </div>
  <%= render :partial =>"layouts/partials/front_menu"%>
  <%= render :partial => "layouts/partials/inside_menu"%>
</header>

app/views/layouts/partials/_inside_menu.html.erb
<div id="menu">
<div id ="sMenu">
  <ul>
  <li><%= link_to "Główna", root_path %></li>
  <%if user_signed_in?%>
  <li><%= link_to "Mapa", user_path(@user)%>
  </li>
  <li><%= link_to "Galeria", user_photos_path(@user)%></li>
  <li><%= link_to "Użytkownicy", users_path %></li>
  <li><%= link_to "Profil", profile_users_path(:id => @user.id)%>
  </li>
  <% end %>
  <li><%= link_to "O nas", about_path %></li>
  </ul>
</div>
</div>